export default [
  ['Pajazzo', 'http://www.royalravintolat.com/casinohelsinki/piazza-lounas'],
  ['Factory Aleksi', 'http://www.ravintolafactory.com/aleksi/lounas/'],
  ['Mount Everest Vilhola', 'http://www.everestyeti.fi/fi/vilhola/lounas.php'],
  ['Base Camp', 'http://www.basecampnepal.fi/lounaslista'],
  ['Maya', 'http://www.maya.fi/lounaat.php'],
  ['Kitzens Radisson Blu Plaza', 'http://www.raflaamo.fi/helsinki/kitzens-helsinki-radisson-blu-plaza#navigation_raflaamolunchmenuportlet_war_raflaamorestaurantportlet'],
  ['Tablo Ateneum', 'https://www.facebook.com/TabloAteneum'],
  ['Il Siciliano', 'http://ilsiciliano2.fi/lounas/'],
  ['La Torrefazione', 'http://www.latorre.fi/'],
  ['Fratello Torrefazione', 'http://fratello.fi/'],
  ['Woolshed', 'http://www.woolshed.eu/#!lounas-menu/ceik'],
  ['Armas', 'http://armashelsinki.fi/'],
  ['Belge', 'http://www.belge.fi/belge-lounas.html'],
  ['Morrisonʼs', 'http://www.lounaat.fi/#morrisons'],
  ['Memphis Hesari', 'http://www.raflaamo.fi/fi/helsinki/memphis-hesari#navigation_raflaamolunchmenuportlet_war_raflaamorestaurantportlet'],
  ['Leonardo', 'http://www.leonardobarristorante.fi/lounas'],
  ['Sports Academy', 'http://www.sportsacademy.fi/lounas.html'],
  ['Shanghai Cowboy', 'https://www.facebook.com/ShanghaiCowboyHKI/'],
  ['Pompier Espa', 'http://pompier.fi/espa/lounas/'],
]

// RIP
// ['Café Balzac', 'http://www.cafebalzac.fi/menu.php'],
// ['Meze Point', 'http://www.meze.fi/lounas'],
